hash-format = "sha256"

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "78a2974be4ca1553dc4d339f6ebe6eee69e3113389b2fea2667a3678cf207c29"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "aa8adc794cf6f3d5b641a1fcea9f5a2b7028009f19b226ce14160dd971c48993"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "1c0b0019300b6e06e87249b0f8843dbc6a0ed19e0c679320c69dda9775b7740f"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "d13b5ed170c859a08389d9b3357377dbae4e3eac32cab6452baf796f98c734f2"
metafile = true

[[files]]
file = "mods/astral-sorcery.pw.toml"
hash = "7ef88dc078a14cc042eec4484a3ae9e9b2c0e429dd1f7e86144b636464f6ba9e"
metafile = true

[[files]]
file = "mods/beyond-earth.pw.toml"
hash = "8eb997d963fe378b056fd2bd07ec35191cf41adad9c19d13d88516444ddcf14a"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "13cd496ddec6be5c7ce0114e24f893a8bf9bee38efd3e3f9e4fae1b9736cb927"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "7c687313824a8742a05f4971460502743f728718b4d87190bc55afe6087c0527"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "3c9aa8445a66ff937c82f5fe09eb914eb4e71c423b8ea5543ace6a25ec2bf5e8"
metafile = true

[[files]]
file = "mods/chisels-bits.pw.toml"
hash = "972234d5c9cd6b408830a54d87b688622972b70a55394bd430d80d8051acb29d"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "02d3751895e1aea3675afb6d16424e4dcefdcf8c3fe9c486fda53b250e624ced"
metafile = true

[[files]]
file = "mods/cleancut.pw.toml"
hash = "9a695ebd699ca3b3e03e7a2a1fe3e7fe05cfabb558a19ca08c96cb63f32483a5"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "1a01ec8a8ca02d7eb862ee1d31752f265b2dd22e03c1e17c9950f5c7cccdd90b"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "c26308548643945934745be773754649df081cd5163b90f1f805a7eced96e1f8"
metafile = true

[[files]]
file = "mods/common-capabilities.pw.toml"
hash = "f786da387c38f985d46d00c765ced150a88e5a65177bf3d7e4091bd43e87720e"
metafile = true

[[files]]
file = "mods/corail-tombstone.pw.toml"
hash = "b552ca18e38236440ce6e02632cf30f6c4922a5b6b6aaf5d7fb0e05c0197d72a"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "cf6a575860bb0c9ce92aa33ccf881a6a57363914f3c83487e9743f063fef7a91"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "c6939bf4325d6cf14906518a21beb562541fb37ea97746de43f6527a58d6d184"
metafile = true

[[files]]
file = "mods/culinary-construct.pw.toml"
hash = "9e2108045a16161bcd48f757e9a4a2eabbd75d5adca17e481c04c4c8f7c9e0ef"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "88de9e0b66391586d0764e8fcca14bf6850a99ea030027bbf7946dafefcd0d5a"
metafile = true

[[files]]
file = "mods/cyclops-core.pw.toml"
hash = "53bb90dd6a039ae924a4e796c3b5b1dc69f1941b9dc47fb05c88c3c75ed544ca"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
hash = "9a8c4e1f33f6f5349e7fd841734fa1db255a9a2e531cfc35c43163da3986ea87"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
hash = "7784bbe87c156cdc99cce7ea79cc2d7d96580f716848e33ab215a31351625a61"
metafile = true

[[files]]
file = "mods/fastfurnace-minus-replacement.pw.toml"
hash = "dcad310128e57f1af4d44929bab03a2cec33861931f84f8591db1e4536c4e52e"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "62ce1c71f37c4b66e0a4b160c9815762017b4862f96523f04029dd8d72bb4f13"
metafile = true

[[files]]
file = "mods/flywheel.pw.toml"
hash = "9a643dece883f4eaa644aff19903b40b6ef2e2c5b9e8692c8c4c19d793618304"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "dca9f36f6ed042e6d5799b0eab64e76ee4d847fbfff46748d21478fcff274239"
metafile = true

[[files]]
file = "mods/guide-api-village-and-pillage.pw.toml"
hash = "55ca37f991d6f281c54b7e3fb9880724d996f695015517adce348e08c69226e2"
metafile = true

[[files]]
file = "mods/immersive-engineering.pw.toml"
hash = "8877652862afaca46d384d624aa036defb3da680a804e2f033019c9794c8c785"
metafile = true

[[files]]
file = "mods/integrated-dynamics.pw.toml"
hash = "c4d1fd9068795f095279bd07aab45328ffca5abc272394a4c423ece7fff64104"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "6ae83f538a16deb321452e65aeb195b4d2d2a4372dc6e48c0531ddee7b7fb3f3"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "7edc90a4c9d38b882798d87a444e87893597bcab46a9e5226c8f83d9515c895c"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
hash = "5c3104aa14ce4122f0a33c5ee041884714cae5a7592e402237742090bc40e20b"
metafile = true

[[files]]
file = "mods/new-tardis-mod.pw.toml"
hash = "1ec19026e1b2ee1a2a9021f10dbf734f20d1f2ddf18696f1166f14c791984f1f"
metafile = true

[[files]]
file = "mods/observerlib.pw.toml"
hash = "8a2ae2e0314307a913514d5447466e3a50cc00a78e936e4e6be4497a406afa56"
metafile = true

[[files]]
file = "mods/occultism.pw.toml"
hash = "cdb113f48239a9d46eb4a4138715cfb2da035e4917fcb7f156a0c5214b286a37"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "e94940367c4862d0c9285471514413faf2e2be9e1c585085d5de045f8e9fd87a"
metafile = true

[[files]]
file = "mods/portality.pw.toml"
hash = "d92bc5bd4122fd28d1f977e536742c2f0f0e2d46b06b972498e9f90d79448a10"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "a77d696645a9d2789279052697c47ae9744437ba945c1b74ab178de986916166"
metafile = true

[[files]]
file = "mods/snow-under-trees.pw.toml"
hash = "901f0b0321a689fca56181064b917a66fea77f9e85adbecf689b869d315fc598"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "c06c497e708ac45f3643b1784d77bff1d6a060c77efadce3b792826d95a15d99"
metafile = true

[[files]]
file = "mods/the-one-probe.pw.toml"
hash = "7fb57ea0506bf6ee41a93cb60745adc9d7ba1055ac14135ff311c5fdd3efbe44"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "1dda287b20d9afec27864e9625dc7c4017f66ece39e117c10dcd97edc42c68a3"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "5117466a8047ccafae0fbbdf83f461bf0cec9747610f8327aae183895cdc6d2f"
metafile = true

[[files]]
file = "mods/vampires-need-umbrellas.pw.toml"
hash = "3f74448e2b8ccd59f30a05352f6b83afff353bcce915d3c3cf9d2bf79c21e832"
metafile = true

[[files]]
file = "mods/vampirism-become-a-vampire.pw.toml"
hash = "4e4236e7542b2009bff3d656100ae0dfe7f0783666f82d740d60afc940cc2d26"
metafile = true

[[files]]
file = "mods/werewolves-become-a-beast.pw.toml"
hash = "9e34194f3f02a6797a8d399a7c3a17cadb4e08c7b17bb47c1999261315d126ab"
metafile = true

[[files]]
file = "mods/wizard-staff.pw.toml"
hash = "d02fe04a872231572ee7512b394e94b6430a3a7e76291b95ff446ed54671d25e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "8521d7d02cdea91ceac85ebe535ad247de14067e37159691703187bb37667625"
metafile = true
